const { onRequest } = require('firebase-functions/v2/https');
const { setGlobalOptions } = require('firebase-functions/v2');
const admin = require('firebase-admin');
const crypto = require('crypto');
const nodemailer = require('nodemailer');
admin.initializeApp();
setGlobalOptions({ region: 'asia-southeast1', maxInstances: 10, timeoutSeconds: 60 });
const db = admin.firestore();
const cors = res => { res.set('Access-Control-Allow-Origin','*'); res.set('Access-Control-Allow-Headers','Content-Type, Authorization'); res.set('Access-Control-Allow-Methods','POST, OPTIONS'); };
const body = req => (req.body && typeof req.body === 'object' ? req.body : {});
const hash = v => crypto.createHash('sha256').update(String(v)).digest('hex');
const makeOtp = () => String(crypto.randomInt(100000, 1000000));
async function verifyBearer(req){ const token=String(req.get('Authorization')||'').replace(/^Bearer\s+/i,''); if(!token) throw Object.assign(new Error('Phiên đăng nhập không hợp lệ.'),{status:401}); return admin.auth().verifyIdToken(token); }
async function sendOtpEmail(to, code){ const user=process.env.GMAIL_SMTP_USER; const pass=process.env.GMAIL_SMTP_APP_PASSWORD; const from=process.env.GMAIL_SMTP_FROM||user; if(!user||!pass) throw new Error('Chưa cấu hình Gmail SMTP.'); const tx=nodemailer.createTransport({service:'gmail',auth:{user,pass}}); await tx.sendMail({from,to,subject:'Mã xác thực GP Statistical',html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h2>GP Statistical</h2><p>Mã xác thực email của bạn:</p><div style="font-size:36px;font-weight:900;letter-spacing:10px;padding:18px 0">${code}</div><p>Mã có hiệu lực trong 10 phút và chỉ sử dụng một lần.</p></div>`}); }
exports.sendVerification=onRequest(async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});try{const decoded=await verifyBearer(req);const email=String(body(req).email||'').trim().toLowerCase();if(email!==String(decoded.email||'').toLowerCase()||!decoded.email_verified)return res.status(403).json({error:'Gmail Google chưa được xác thực hoặc không khớp phiên đăng nhập.'});if(!email.endsWith('@gmail.com'))return res.status(400).json({error:'Chỉ chấp nhận Gmail.'});const profile=await db.collection('users').doc(decoded.uid).get();if(profile.exists&&profile.data()?.emailVerified)return res.status(409).json({error:'Tài khoản đã được xác thực.'});const ref=db.collection('verificationSessions').doc(decoded.uid);const prev=await ref.get();if(prev.exists){const last=prev.data()?.sentAt?.toMillis?.()||0;if(Date.now()-last<60000)return res.status(429).json({error:'Vui lòng chờ 60 giây trước khi gửi lại mã.'});}const code=makeOtp();await ref.set({uid:decoded.uid,email,codeHash:hash(`${decoded.uid}:${code}`),attempts:0,expiresAt:admin.firestore.Timestamp.fromMillis(Date.now()+10*60*1000),sentAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});await sendOtpEmail(email,code);res.json({ok:true});}catch(e){console.error(e);res.status(e.status||500).json({error:e.message||'Không gửi được mã xác thực.'});}});
exports.verifyGoogle=onRequest(async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});try{const decoded=await verifyBearer(req);const email=String(body(req).email||'').trim().toLowerCase();const code=String(body(req).code||'').trim();if(String(decoded.email||'').toLowerCase()!==email||!decoded.email_verified)return res.status(403).json({error:'Email không khớp tài khoản Google.'});if(!/^\d{6}$/.test(code))return res.status(400).json({error:'Mã xác thực phải gồm đúng 6 số.'});const ref=db.collection('verificationSessions').doc(decoded.uid);const snap=await ref.get();if(!snap.exists)return res.status(400).json({error:'Không tìm thấy phiên xác thực. Hãy gửi mã mới.'});const v=snap.data();if(v.expiresAt.toMillis()<Date.now())return res.status(400).json({error:'Mã đã hết hạn. Hãy gửi mã mới.'});if((v.attempts||0)>=5)return res.status(429).json({error:'Bạn đã nhập sai quá số lần cho phép.'});if(hash(`${decoded.uid}:${code}`)!==v.codeHash){await ref.update({attempts:admin.firestore.FieldValue.increment(1)});return res.status(400).json({error:'Mã xác thực không đúng.'});}await db.collection('users').doc(decoded.uid).set({uid:decoded.uid,email,displayName:decoded.name||'',photoURL:decoded.picture||'',emailVerified:true,notificationEmail:true,createdAt:admin.firestore.FieldValue.serverTimestamp(),verifiedAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});await ref.delete();res.json({ok:true});}catch(e){console.error(e);res.status(e.status||500).json({error:e.message||'Không xác thực được email.'});}});
function folderIdFromUrl(raw){const s=String(raw||'').trim();const m=s.match(/\/folders\/([A-Za-z0-9_-]+)/)||s.match(/[?&]id=([A-Za-z0-9_-]+)/);return m?m[1]:null;}
async function driveFetch(path,params={}){const key=process.env.GOOGLE_DRIVE_API_KEY;if(!key)throw Object.assign(new Error('GOOGLE_DRIVE_API_KEY chưa được cấu hình.'),{status:500});const u=new URL(`https://www.googleapis.com/drive/v3/${path}`);for(const [k,v] of Object.entries(params))if(v!==undefined&&v!=='')u.searchParams.set(k,String(v));u.searchParams.set('key',key);const r=await fetch(u);const text=await r.text();if(!r.ok){let detail='';try{detail=JSON.parse(text)?.error?.message||''}catch{}throw Object.assign(new Error(detail||'Không thể truy cập Google Drive.'),{status:r.status===401||r.status===403||r.status===404?403:r.status});}return JSON.parse(text);}
async function listChildren(parentId){const files=[];let token='';do{const d=await driveFetch('files',{q:`'${parentId}' in parents and trashed = false`,pageSize:1000,fields:'nextPageToken,files(id,name,mimeType,webViewLink,thumbnailLink,size,modifiedTime)',...(token?{pageToken:token}:{})});files.push(...(d.files||[]));token=d.nextPageToken||'';}while(token);return files;}
exports.scanDrive=onRequest(async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});try{await verifyBearer(req);const rootId=folderIdFromUrl(body(req).url);if(!rootId)return res.status(400).json({error:'Link Google Drive không hợp lệ. Hãy dán link thư mục.'});const root=await driveFetch(`files/${rootId}`,{fields:'id,name,mimeType,webViewLink'});if(root.mimeType!=='application/vnd.google-apps.folder')return res.status(400).json({error:'Link phải trỏ tới một thư mục Google Drive.'});const queue=[{id:root.id,path:[root.name],depth:0}],items=[],seen=new Set([root.id]);let scannedFolders=0;while(queue.length&&scannedFolders<1000&&items.length<1000){const cur=queue.shift();scannedFolders++;const children=await listChildren(cur.id);const folders=children.filter(f=>f.mimeType==='application/vnd.google-apps.folder');const files=children.filter(f=>f.mimeType!=='application/vnd.google-apps.folder');if(files.length){const text=`${cur.path.join(' / ')} ${files.map(f=>f.name).join(' ')}`;const volume=(text.match(/\b\d+(?:[.,]\d+)?\s*(?:ml|l|kg|g)\b/i)||[])[0]||'';const size=(text.match(/\b\d{2,5}\s*[x×]\s*\d{2,5}(?:\s*[x×]\s*\d{2,5})?\b/i)||[])[0]||'';const quantity=Number((text.match(/(?:qty|quantity|sl)\s*[:_-]?\s*(\d+)/i)||[])[1]||1);const images=files.filter(f=>String(f.mimeType||'').startsWith('image/')).slice(0,8);items.push({id:cur.id,name:cur.path.at(-1),productName:cur.path.at(-1),volume,size,quantity,path:cur.path.join(' / '),url:`https://drive.google.com/drive/folders/${cur.id}`,images:images.map(f=>({id:f.id,name:f.name,url:`https://drive.google.com/thumbnail?id=${f.id}&sz=w1000`,driveUrl:f.webViewLink||`https://drive.google.com/open?id=${f.id}`})),files:files.slice(0,30).map(f=>({id:f.id,name:f.name,mimeType:f.mimeType,url:f.webViewLink||`https://drive.google.com/open?id=${f.id}`}))});}for(const folder of folders)if(cur.depth<8&&!seen.has(folder.id)){seen.add(folder.id);queue.push({id:folder.id,path:[...cur.path,folder.name],depth:cur.depth+1});}}res.json({ok:true,root:{id:root.id,name:root.name,url:root.webViewLink||`https://drive.google.com/drive/folders/${root.id}`},scannedFolders,items});}catch(e){console.error(e);if(e.status===403)return res.status(403).json({error:'Không thể truy cập thư mục Google Drive. Hãy vào Chia sẻ → Quyền truy cập chung → Anyone with the link → Viewer rồi thử lại.',code:'DRIVE_NOT_PUBLIC'});res.status(e.status||500).json({error:e.message||'Không thể quét Google Drive.'});}});
