import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged, setPersistence, browserLocalPersistence } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, deleteDoc, collection, addDoc, onSnapshot, query, orderBy, getDocs, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyCVY90upeKcuR5u8VPzqNmI-TFe2CDSL14',authDomain:'gp-statistical.firebaseapp.com',projectId:'gp-statistical',storageBucket:'gp-statistical.firebasestorage.app',messagingSenderId:'870570090818',appId:'1:870570090818:web:0a140685c61b3ec95ea8db',measurementId:'G-XN7Y4JYJLT'};
const appFb=initializeApp(firebaseConfig),auth=getAuth(appFb),db=getFirestore(appFb);
await setPersistence(auth,browserLocalPersistence);
const provider=new GoogleAuthProvider();

const LEGACY='ventek-design-tracker-v2', SETTINGS='ventek-design-settings-v2', WORKSPACE='gp-statistical';
const FOLDER='application/vnd.google-apps.folder', IMAGE=/\.(png|jpe?g|webp|gif|bmp|tiff?|svg)$/i, ASSET=/\.(png|jpe?g|webp|gif|bmp|tiff?|svg|pdf|ai|psd|eps|indd|zip)$/i;
const VOL_FILE=/((?:\d+(?:[.,]\d+)?)\s?(?:ml|cl|l|lit|liter|litre))(?=\b|[_ .-])/i, VOL_FOLDER=/^\s*\d+(?:[.,]\d+)?\s*(?:ml|cl|l|lit|liter|litre)\s*$/i;
const SIZE_FILE=/\b(\d{2,5}\s*[x×]\s*\d{2,5}|A[0-6])\b/i, SIZE_FOLDER=/^\s*(?:\d{2,5}\s*[x×]\s*\d{2,5}|A[0-6])\s*$/i;
const ROLE_DIR=/^(?:\d{1,2}\s*[-_.]\s*)?(final|source|mockup|draft|preview|output|print|artwork|file)$/i;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\\/g,'/').replace(/\s+/g,' ').trim().toLowerCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const driveUrl=id=>id?`https://drive.google.com/drive/folders/${id}`:'';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const defaults={designers:['Gia Phú'],customers:[],editTypes:['Design mới','Sửa thông tin','Update thông tin','Sửa kích thước'],googleClientId:'',pageSize:50};
const state={user:null,role:null,members:[],invites:[],records:[],settings:{...defaults,...load(SETTINGS,{})},view:'dashboard',month:new Date().toISOString().slice(0,7),search:'',customer:'',filters:[],driveToken:null,scanRows:[],shareMode:false,shareId:'',shareDoc:null,shareRecords:[],lastSaveBy:'',loading:false};
const root=document.querySelector('#app');
let unsubProducts=null,unsubMembers=null,unsubShare=null,unsubShareProducts=null;

function cacheRecords(rs){try{localStorage.setItem(LEGACY,JSON.stringify(rs))}catch{}}
function getLegacy(){return load(LEGACY,[]).map(r=>({...r,assets:Array.isArray(r.assets)?r.assets:[],editTypes:Array.isArray(r.editTypes)?r.editTypes:(r.editTypes?[r.editTypes]:[])}))}
function monthLabel(m){if(!m)return'Tất cả tháng';const [y,mo]=m.split('-');return `${mo}/${y}`}
function volumeFrom(s){const m=String(s||'').match(VOL_FILE);return m?m[1].replace(/\s+/g,'').replace(/lit(?:er|re)?$/i,'L').replace(/l$/i,'L'):''}
function sizeFrom(s){const m=String(s||'').match(SIZE_FILE);return m?m[1].replace(/\s+/g,'').replace('×','x').toUpperCase():''}
function cleanName(s){return String(s||'').replace(/\.[^.]+$/,'').replace(/^\d{1,2}\s*[-_.]\s*/,'').replace(/[_-]+$/,'').trim()}
function productFrom(file,path,variantIndex){let n=cleanName(file).replace(VOL_FILE,'').replace(SIZE_FILE,'').replace(/\b(final|source|mockup|draft|preview|output|print|artwork|design|image|img|update)\b/ig,'').replace(/[_-]+/g,' ').replace(/\s{2,}/g,' ').trim();if(!n){const v=variantIndex>0?path[variantIndex-1]:path[path.length-2];n=cleanName(v||'')}return n}
function variantInfo(file,path,ancestors){for(let i=ancestors.length-1;i>=0;i--){const a=ancestors[i];if(VOL_FOLDER.test(a.name)||SIZE_FOLDER.test(a.name))return {id:a.id,name:a.name,pathIndex:i,volume:volumeFrom(a.name),size:sizeFrom(a.name)}}const v=volumeFrom(file)||[...path].reverse().map(volumeFrom).find(Boolean)||'';const s=sizeFrom(file)||[...path].reverse().map(sizeFrom).find(Boolean)||'';return {id:'',name:'',pathIndex:-1,volume:v,size:s}}
function roleFor(name,path){const d=[...path].reverse().find(x=>ROLE_DIR.test(x));if(d)return cleanName(d).toLowerCase();if(/final/i.test(name))return'final';if(/mockup/i.test(name))return'mockup';if(/source/i.test(name))return'source';return'asset'}

async function driveApi(url,token=state.driveToken){if(!token)throw Error('Google Drive chưa kết nối.');const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){if(r.status===401){state.driveToken=null;throw Error('Quyền Google Drive đã hết hạn. Hãy bấm Kết nối Google Drive.')}let e='';try{e=(await r.json()).error?.message||''}catch{}throw Error(e||`Google Drive lỗi ${r.status}`)}return r.json()}
function driveTokenOnce(prompt='consent'){return new Promise((resolve,reject)=>{if(!state.settings.googleClientId)return reject(Error('Chưa cấu hình Google Drive OAuth Client ID trong Cài đặt.'));if(!window.google?.accounts?.oauth2)return reject(Error('Google Identity Services chưa tải xong.'));const c=google.accounts.oauth2.initTokenClient({client_id:state.settings.googleClientId,scope:'https://www.googleapis.com/auth/drive.readonly',include_granted_scopes:true,callback:r=>r?.access_token?resolve(r.access_token):reject(Error(r?.error_description||r?.error||'Không lấy được quyền Drive'))});c.requestAccessToken({prompt})})}
async function ensureDrive(prompt=''){if(state.driveToken)return state.driveToken;state.driveToken=await driveTokenOnce(prompt||'consent');return state.driveToken}
async function listTree(rootId){const folders=new Map(),files=[];const root=await driveApi(`https://www.googleapis.com/drive/v3/files/${rootId}?fields=id,name,mimeType,webViewLink`);async function walk(id,path,anc){folders.set(id,{id,name:path[path.length-1]||root.name,path:[...path],ancestors:[...anc]});let page='';do{const q=encodeURIComponent(`'${id}' in parents and trashed=false`),fields=encodeURIComponent('nextPageToken,files(id,name,mimeType,modifiedTime,version,size,webViewLink,thumbnailLink)');let u=`https://www.googleapis.com/drive/v3/files?q=${q}&pageSize=1000&fields=${fields}`;if(page)u+=`&pageToken=${encodeURIComponent(page)}`;const d=await driveApi(u);for(const f of d.files||[]){if(f.mimeType===FOLDER)await walk(f.id,[...path,f.name],[...anc,{id:f.id,name:f.name}]);else if(ASSET.test(f.name))files.push({...f,folderPath:[...path],ancestors:[...anc]})}page=d.nextPageToken||''}while(page)}await walk(rootId,[],[]);return{root,folders,files}}
function scanTree(tree){const groups=new Map();for(const f of tree.files){const v=variantInfo(f.name,f.folderPath,f.ancestors),p=productFrom(f.name,f.folderPath,v.pathIndex),key=v.id?`folder:${v.id}`:`fallback:${tree.root.id}|${norm(p)}|${norm(v.volume)}|${norm(v.size)}|${f.folderPath.join('\0')}`;if(!groups.has(key))groups.set(key,{id:uid(),productName:p,volume:v.volume,size:v.size,quantity:1,variantFolderId:v.id,variantFolderName:v.name,driveRootFolderId:tree.root.id,driveRootFolderUrl:tree.root.webViewLink||driveUrl(tree.root.id),driveFolderUrl:v.id?driveUrl(v.id):tree.root.webViewLink||driveUrl(tree.root.id),sourceFolderPath:[tree.root.name,...f.folderPath].join(' / '),assets:[]});const g=groups.get(key);g.assets.push({id:f.id,name:f.name,mimeType:f.mimeType||'',modifiedTime:f.modifiedTime||'',version:f.version||'',size:f.size||'',webViewLink:f.webViewLink||`https://drive.google.com/open?id=${f.id}`,thumbnailLink:f.thumbnailLink||'',folderPath:[tree.root.name,...f.folderPath].join(' / '),role:roleFor(f.name,f.folderPath)})}for(const g of groups.values()){g.assets.sort((a,b)=>(a.role==='final'?0:1)-(b.role==='final'?0:1)||String(b.modifiedTime).localeCompare(String(a.modifiedTime)));g.previewAssets=g.assets.filter(a=>IMAGE.test(a.name)).sort((a,b)=>{const sa=a.name.match(/(?:_|[- ])(0[12])(?:\.[^.]+)$/i)?.[1]||'99',sb=b.name.match(/(?:_|[- ])(0[12])(?:\.[^.]+)$/i)?.[1]||'99';return sa.localeCompare(sb)}).slice(0,2);g.previewFileId=g.previewAssets[0]?.id||'';g.previewFileName=g.previewAssets[0]?.name||''}return[...groups.values()]}

function filteredRecords(){return state.records.filter(r=>{if(state.month&&r.month!==state.month)return false;if(state.customer&&r.customer!==state.customer)return false;const h=norm(`${r.customer} ${r.productName} ${r.volume} ${r.size} ${r.designer} ${(r.editTypes||[]).join(' ')}`);if(state.search&&!h.includes(norm(state.search)))return false;return state.filters.every(f=>{const val=norm(f.field==='editTypes'?(r.editTypes||[]).join(' '):r[f.field]||'');const t=norm(f.value);return f.op==='equals'?val===t:f.op==='not'?val!==t:val.includes(t)})})}
function summary(d){const counts={};d.forEach(r=>(r.editTypes||[]).forEach(t=>counts[t]=(counts[t]||0)+1));return {products:d.length,qty:d.reduce((n,r)=>n+Number(r.quantity||0),0),counts}};
function htmlStats(d){const s=summary(d);return `<section class="grid"><div class="stat card"><span>TỔNG SỐ SẢN PHẨM</span><b>${s.products}</b>${Object.entries(s.counts).filter(([,n])=>n).map(([k,n])=>`<small>${esc(k)}: ${n}</small>`).join('')}</div><div class="stat card"><span>TỔNG SỐ LƯỢNG</span><b>${s.qty}</b></div><div class="stat card"><span>THÁNG</span><b>${esc(monthLabel(state.month))}</b></div><div class="stat card"><span>NGƯỜI THỰC HIỆN</span><b>${new Set(d.map(r=>r.designer).filter(Boolean)).size}</b></div></section>`}
function imagesHtml(r){return `<div class="thumbs">${(r.previewAssets||[]).slice(0,2).map(a=>`<button class="image-btn" data-image="${esc(a.id)}"><img src="${esc(a.thumbnailLink||'')}" alt="${esc(a.name)}"></button>`).join('')||'<span class="image-empty">—</span>'}</div>`}
function tableHtml(d,editable=true){return `<section class="card table-card"><div class="toolbar"><div><b>Danh sách sản phẩm</b><span class="count">${d.length} dòng</span></div><div class="actions"><button class="btn" id="exportXlsx">Xuất Excel</button><button class="btn" id="exportPdf">Xuất PDF / A4</button><button class="btn primary" id="shareBtn">Chia sẻ</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Hình</th><th>Khách hàng</th><th>Sản phẩm</th><th>Size</th><th>Thể tích</th><th>SL</th><th>Designer</th><th>Công việc</th><th>Ngày</th><th>Drive</th>${editable?'<th></th>':''}</tr></thead><tbody>${d.length?d.map(r=>`<tr><td>${imagesHtml(r)}</td><td>${esc(r.customer||'')}</td><td><strong>${esc(r.productName||'')}</strong><small>${esc(r.sourceFolderPath||'')}</small></td><td>${esc(r.size||'—')}</td><td>${esc(r.volume||'—')}</td><td>${esc(r.quantity||0)}</td><td>${esc(r.designer||'')}</td><td>${(r.editTypes||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join(' ')}</td><td>${esc(r.date||'')}</td><td>${r.driveVariantFolderId?`<a class="link" target="_blank" rel="noopener" href="${esc(driveUrl(r.driveVariantFolderId))}">Mở variant ↗</a>`:'—'}</td>${editable?`<td class="edit-actions"><button class="btn small" data-edit="${r.id}">Sửa</button><button class="btn small danger" data-delete="${r.id}">Xóa</button></td>`:''}</tr>`).join(''):'<tr><td colspan="11" class="empty">Không có dữ liệu.</td></tr>'}</tbody></table></div></section>`}
function sidebar(){return `<aside class="sidebar"><div class="brand">GP <span>STATISTICAL</span><small>Design & Product Tracker</small></div><nav class="nav">${[['dashboard','⌂','Tổng quan'],['list','▤','Bảng kê'],['stats','◒','Thống kê'],['share','↗','Chia sẻ'],['settings','⚙','Cài đặt']].map(x=>`<button data-view="${x[0]}" class="${state.view===x[0]?'active':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}<button id="addNav" class="add-nav"><b>＋</b>Thêm sản phẩm</button></nav><div class="side-bottom"><div class="connection"><strong><i class="status-dot ok"></i>${esc(state.user?.displayName||state.user?.email||'')}</strong><span>${esc(state.role||'member')}</span><button id="logoutBtn" class="gp-logout">Đăng xuất</button></div></div></aside>`}
function header(title,sub){return `<div class="top"><div><div class="eyebrow">GP STATISTICAL</div><h1 class="title">${title}</h1><div class="muted">${sub}</div></div><div class="actions"><button class="btn" id="driveBtn">${state.driveToken?'✓ Drive đã kết nối':'Kết nối Google Drive'}</button><button class="btn primary" id="addBtn">＋ Thêm sản phẩm</button></div></div>`}
function filterBar(){return `<div class="filters"><select id="customerFilter" class="input"><option value="">Tất cả khách hàng</option>${state.settings.customers.map(c=>`<option ${c===state.customer?'selected':''}>${esc(c)}</option>`).join('')}</select><input id="monthFilter" class="input" type="month" value="${esc(state.month)}"><input id="searchFilter" class="input wide" value="${esc(state.search)}" placeholder="Tìm kiếm…"><button class="btn ghost" id="clearFilter">Xóa lọc</button></div>`}
function render(){if(state.shareMode){renderShare();return}if(!state.user){root.innerHTML=`<div class="gate"><div class="gate-card"><div class="gate-kicker">GP STATISTICAL</div><h1>Quản lý sản phẩm.</h1><p>Đăng nhập bằng Google để xem dữ liệu của workspace. Phiên đăng nhập được Firebase duy trì trên trình duyệt, nên reload không cần đăng nhập lại.</p><button class="btn" id="loginBtn">Đăng nhập bằng Google</button><span class="gate-note">Google Drive là quyền riêng cho việc đọc file; đăng nhập ứng dụng không phụ thuộc Drive.</span></div></div>`;document.querySelector('#loginBtn').onclick=()=>signInWithPopup(auth,provider).catch(e=>toast(e.message));return}const d=filteredRecords();let body='';if(state.view==='list')body=`${header('Bảng kê',`Tháng ${monthLabel(state.month)} · ${d.length} sản phẩm`)}${filterBar()}${htmlStats(d)}${tableHtml(d,true)}`;else if(state.view==='stats')body=`${header('Thống kê',`Phân tích ${monthLabel(state.month)}`)}${filterBar()}${htmlStats(d)}<div class="chart-grid"><section class="card"><h2>Theo khách hàng</h2>${bars(d,'customer')}</section><section class="card"><h2>Theo designer</h2>${bars(d,'designer')}</section></div>`;else if(state.view==='share')body=`${header('Chia sẻ','Tạo và quản lý liên kết xem / cộng tác')}<section class="card"><div class="section-head"><div><h2>Chia sẻ workspace</h2><span class="muted">Một liên kết ổn định, dữ liệu cập nhật realtime.</span></div><button class="btn primary" id="newShare">＋ Tạo liên kết xem</button></div><div id="sharesBox">Đang tải…</div></section><section class="card"><h2>Thành viên</h2><div class="filters"><input id="inviteEmail" class="input" placeholder="email@gmail.com"><select id="inviteRole" class="select"><option value="viewer">Người xem</option><option value="editor">Người chỉnh sửa</option></select><button id="inviteBtn" class="btn primary">Mời</button></div><div id="membersBox"></div></section>`;else if(state.view==='settings')body=renderSettings();else body=`${header('Tổng quan',`Tháng ${monthLabel(state.month)} · ${d.length} sản phẩm`)}${filterBar()}${htmlStats(d)}<div class="chart-grid"><section class="card"><div class="section-head"><div><h2>Công việc tháng này</h2><span class="muted">Dữ liệu Firestore realtime</span></div><button class="btn" data-view="list">Mở bảng kê</button></div>${bars(d,'editTypes')}</section><section class="card"><div class="section-head"><div><h2>Mới cập nhật</h2></div></div>${tableHtml(d.slice(0,8),true)}</section></div>`;root.innerHTML=`<div class="shell">${sidebar()}<main class="main">${body}</main></div>`;bind();}
function bars(d,field){if(field==='editTypes'){const m={};d.forEach(r=>(r.editTypes||[]).forEach(x=>m[x]=(m[x]||0)+1));return Object.entries(m).map(([k,n])=>`<div class="stat-line"><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<div class="empty">—</div>'}const vals=[...new Set(d.map(r=>r[field]).filter(Boolean))];return vals.map(k=>`<div class="bar-line"><span>${esc(k)}</span><div class="bar-track"><i style="width:${Math.max(6,100*d.filter(r=>r[field]===k).length/Math.max(1,d.length))}%"></i></div><b>${d.filter(r=>r[field]===k).length}</b></div>`).join('')||'<div class="empty">—</div>'}
function renderSettings(){return `${header('Cài đặt','Tài khoản, OAuth Drive và danh mục')}<section class="card"><div class="section-head"><div><h2>Tài khoản</h2><span class="muted">${esc(state.user?.email||'')}</span></div></div><p class="field-help">Đăng nhập ứng dụng dùng Firebase. Quyền Drive chỉ dùng khi đọc folder/file và không quyết định việc dữ liệu có hiển thị hay không.</p></section><section class="card"><h2>Google Drive</h2><label class="field"><label>OAuth Client ID</label><input id="clientId" class="input wide" value="${esc(state.settings.googleClientId)}"></label><div class="actions" style="margin-top:12px"><button id="saveClient" class="btn primary">Lưu</button><button id="testDrive" class="btn">Kiểm tra quyền Drive</button></div></section><div class="settings-grid"><section class="card"><h2>Khách hàng</h2><div class="filters"><input id="newCustomer" class="input" placeholder="Tên khách hàng"><button id="addCustomer" class="btn primary">Thêm</button></div><div class="pill-list">${state.settings.customers.map((x,i)=>`<span class="pill">${esc(x)} <button data-rmc="${i}">×</button></span>`).join('')||'—'}</div></section><section class="card"><h2>Designer</h2><div class="filters"><input id="newDesigner" class="input" placeholder="Tên designer"><button id="addDesigner" class="btn primary">Thêm</button></div><div class="pill-list">${state.settings.designers.map((x,i)=>`<span class="pill">${esc(x)} <button data-rmd="${i}">×</button></span>`).join('')}</div></section></div>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector('#addBtn')?.addEventListener('click',openAdd);document.querySelector('#addNav')?.addEventListener('click',openAdd);document.querySelector('#driveBtn')?.addEventListener('click',()=>ensureDrive('consent').then(()=>{toast('Google Drive đã kết nối');render()}).catch(e=>toast(e.message)));document.querySelector('#logoutBtn')?.addEventListener('click',()=>signOut(auth));document.querySelector('#customerFilter')?.addEventListener('change',e=>{state.customer=e.target.value;render()});document.querySelector('#monthFilter')?.addEventListener('change',e=>{state.month=e.target.value;render()});const s=document.querySelector('#searchFilter');if(s){s.oninput=()=>{state.search=s.value;updateVisibleTable()};s.onkeydown=e=>{if(e.key==='Enter')updateVisibleTable()}}document.querySelector('#clearFilter')?.addEventListener('click',()=>{state.search='';state.customer='';render()});document.querySelector('#exportXlsx')?.addEventListener('click',()=>exportXlsx(filteredRecords()));document.querySelector('#exportPdf')?.addEventListener('click',()=>exportPdf(filteredRecords()));document.querySelector('#shareBtn')?.addEventListener('click',openShareCreate);document.querySelector('#newShare')?.addEventListener('click',createShare);document.querySelector('#inviteBtn')?.addEventListener('click',inviteMember);document.querySelector('#saveClient')?.addEventListener('click',saveClient);document.querySelector('#testDrive')?.addEventListener('click',()=>ensureDrive('consent').then(()=>toast('Quyền Drive OK')).catch(e=>toast(e.message)));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete));document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>openImage(b.dataset.image));document.querySelectorAll('[data-rmc]').forEach(b=>b.onclick=()=>{state.settings.customers.splice(+b.dataset.rmc,1);saveSettings();render()});document.querySelectorAll('[data-rmd]').forEach(b=>b.onclick=()=>{state.settings.designers.splice(+b.dataset.rmd,1);saveSettings();render()});if(state.view==='share'&&!state.shareMode)renderShareManagement()}
function updateVisibleTable(){const t=document.querySelector('.table-card');if(!t)return;const fresh=tableHtml(filteredRecords(),true);const wrap=document.createElement('div');wrap.innerHTML=fresh;const next=wrap.firstElementChild;t.replaceWith(next);document.querySelector('#exportXlsx')?.addEventListener('click',()=>exportXlsx(filteredRecords()));document.querySelector('#exportPdf')?.addEventListener('click',()=>exportPdf(filteredRecords()));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete));document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>openImage(b.dataset.image))}
function saveSettings(){localStorage.setItem(SETTINGS,JSON.stringify(state.settings));if(state.user)setDoc(doc(db,'workspaces',WORKSPACE),{settings:state.settings,updatedAt:serverTimestamp()},{merge:true}).catch(()=>{})}
async function saveClient(){state.settings.googleClientId=document.querySelector('#clientId').value.trim();saveSettings();toast('Đã lưu Client ID')}

function openAdd(){const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal"><div class="modal-head"><div><h2>Thêm sản phẩm từ Drive</h2><div class="muted">Dán folder bất kỳ. Hệ thống đọc toàn bộ cây bên trong nhưng chỉ lưu các mục bạn chọn.</div></div><button class="btn" id="x">Đóng</button></div><div class="form-grid"><label class="field"><label>Khách hàng</label><input id="c" class="input" list="cl" placeholder="Nhập hoặc chọn"><datalist id="cl">${state.settings.customers.map(x=>`<option>${esc(x)}</option>`).join('')}</datalist></label><label class="field"><label>Tháng</label><input id="m" class="input" type="month" value="${state.month}"></label><label class="field"><label>Designer</label><select id="d" class="select">${state.settings.designers.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label class="field"><label>Công việc</label><select id="e" class="select multi" multiple size="4">${state.settings.editTypes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><label class="field"><label>Link folder Google Drive</label><div class="drive-row"><input id="url" class="input wide" placeholder="https://drive.google.com/drive/folders/..."><button id="scan" class="btn primary">Đọc Drive</button></div></label><div id="st" class="scan-status">Chưa quét.</div><div id="pv"></div><div class="actions" style="justify-content:flex-end"><button class="btn" id="cancel">Hủy</button><button class="btn primary" id="ok" disabled>Thêm mục đã chọn</button></div></div>`;document.body.appendChild(w);w.querySelector('#x').onclick=w.querySelector('#cancel').onclick=()=>w.remove();w.querySelector('#scan').onclick=async()=>{try{const id=(w.querySelector('#url').value.match(/\/folders\/([\w-]+)/)||w.querySelector('#url').value.match(/[?&]id=([\w-]+)/)||[])[1];if(!id)throw Error('Link folder không hợp lệ.');await ensureDrive('consent');const tree=await listTree(id),rows=scanTree(tree).map(r=>({...r,selected:true}));state.scanRows=rows;w.querySelector('#st').className='scan-status ok';w.querySelector('#st').textContent=`Đọc được ${tree.files.length} file → ${rows.length} variant. Bỏ tick các mục cũ trước khi thêm.`;renderScan(w)}catch(e){w.querySelector('#st').className='scan-status err';w.querySelector('#st').textContent=e.message}};}
function renderScan(w){w.querySelector('#pv').innerHTML=`<div class="scan-toolbar"><label><input id="all" type="checkbox" checked> Chọn tất cả</label></div><div class="preview"><table><thead><tr><th></th><th>Hình</th><th>Sản phẩm</th><th>Thể tích</th><th>Size</th><th>Folder chính xác</th><th>File</th></tr></thead><tbody>${state.scanRows.map((r,i)=>`<tr><td><input data-sel="${i}" type="checkbox" ${r.selected?'checked':''}></td><td>${imagesHtml(r)}</td><td><input data-scan="productName" data-i="${i}" value="${esc(r.productName)}"></td><td><input data-scan="volume" data-i="${i}" value="${esc(r.volume)}"></td><td><input data-scan="size" data-i="${i}" value="${esc(r.size)}"></td><td>${esc(r.sourceFolderPath)}</td><td>${r.assets.length}</td></tr>`).join('')}</tbody></table></div>`;w.querySelector('#all').onchange=e=>{state.scanRows.forEach(r=>r.selected=e.target.checked);renderScan(w);w.querySelector('#ok').disabled=false};w.querySelectorAll('[data-sel]').forEach(b=>b.onchange=()=>{state.scanRows[+b.dataset.sel].selected=b.checked;w.querySelector('#ok').disabled=!state.scanRows.some(r=>r.selected)});w.querySelectorAll('[data-scan]').forEach(e=>e.oninput=()=>state.scanRows[+e.dataset.i][e.dataset.scan]=e.value;w.querySelector('#ok').disabled=!state.scanRows.some(r=>r.selected)}

async function upsertProduct(r){const ref=doc(collection(db,'workspaces',WORKSPACE,'products'),r.id||uid());r.id=ref.id;await setDoc(ref,{...r,updatedAt:serverTimestamp(),updatedBy:state.user.uid},{merge:true});await syncSharesForProduct(r)}
async function syncSharesForProduct(r){const qs=await getDocs(query(collection(db,'workspaces',WORKSPACE,'shares'),orderBy('createdAt','desc'))).catch(()=>null);if(!qs)return;for(const s of qs.docs){if(!s.data().active)continue;await setDoc(doc(db,'workspaces',WORKSPACE,'shares',s.id,'products',r.id),r,{merge:true}).catch(()=>{})}}
async function removeProduct(id){if(!confirm('Xóa sản phẩm khỏi bảng kê?'))return;await deleteDoc(doc(db,'workspaces',WORKSPACE,'products',id));const qs=await getDocs(collection(db,'workspaces',WORKSPACE,'shares')).catch(()=>null);if(qs)for(const s of qs.docs)await deleteDoc(doc(db,'workspaces',WORKSPACE,'shares',s.id,'products',id)).catch(()=>{});}
async function editProduct(id){const r=state.records.find(x=>x.id===id);if(!r)return;const p=prompt('Số lượng',String(r.quantity??1));if(p===null)return;r.quantity=Number(p)||1;await upsertProduct(r);toast('Đã cập nhật')}
async function confirmScan(w){const selected=state.scanRows.filter(r=>r.selected);const customer=w.querySelector('#c').value.trim();if(!customer)return toast('Nhập khách hàng.');const month=w.querySelector('#m').value,designer=w.querySelector('#d').value,editTypes=[...w.querySelector('#e').selectedOptions].map(o=>o.value);if(!editTypes.length)return toast('Chọn loại công việc.');for(const v of selected){const r={id:uid(),month,date:new Date().toISOString().slice(0,10),customer,designer,editTypes,quantity:Number(v.quantity)||1,productName:v.productName,volume:v.volume,size:v.size,driveRootFolderId:v.driveRootFolderId,driveRootFolderUrl:v.driveRootFolderUrl,driveVariantFolderId:v.variantFolderId||'',driveFolderUrl:v.driveFolderUrl,sourceFolderPath:v.sourceFolderPath,sourceFileName:v.previewFileName,driveFileId:v.previewFileId,assets:v.assets,previewAssets:v.previewAssets,drivePresent:true};await upsertProduct(r)}if(!state.settings.customers.includes(customer))state.settings.customers.push(customer);saveSettings();w.remove();state.month=month;state.view='list';render()}

async function createShare(){const ref=await addDoc(collection(db,'workspaces',WORKSPACE,'shares'),{name:'GP Statistical',active:true,scope:'workspace',role:'viewer',createdBy:state.user.uid,createdAt:serverTimestamp()});const rs=state.records;for(let i=0;i<rs.length;i+=400){const batch=writeBatch(db);rs.slice(i,i+400).forEach(r=>batch.set(doc(db,'workspaces',WORKSPACE,'shares',ref.id,'products',r.id),r));await batch.commit()}const url=`${location.origin}${location.pathname}#share=${ref.id}`;await navigator.clipboard?.writeText(url).catch(()=>{});toast('Đã tạo liên kết chia sẻ và sao chép URL');render()}
async function revokeShare(id){await updateDoc(doc(db,'workspaces',WORKSPACE,'shares',id),{active:false,revokedAt:serverTimestamp()});toast('Đã thu hồi liên kết')}
async function inviteMember(){const email=document.querySelector('#inviteEmail').value.trim().toLowerCase(),role=document.querySelector('#inviteRole').value;if(!email)return;const key=btoa(email).replace(/=/g,'');await setDoc(doc(db,'workspaces',WORKSPACE,'invites',key),{email,role,workspaceId:WORKSPACE,createdBy:state.user.uid,createdAt:serverTimestamp()});toast(`Đã mời ${email}`);renderShareManagement()}
function renderShareManagement(){const box=document.querySelector('#sharesBox'),mb=document.querySelector('#membersBox');if(!box)return;getDocs(query(collection(db,'workspaces',WORKSPACE,'shares'),orderBy('createdAt','desc'))).then(qs=>{box.innerHTML=qs.docs.length?qs.docs.map(s=>{const x=s.data(),url=`${location.origin}${location.pathname}#share=${s.id}`;return`<div class="stat-line"><span><b>${esc(x.name||'GP Statistical')}</b><br><small>${x.active?'Đang hoạt động':'Đã thu hồi'}</small><br><a class="link" href="${esc(url)}" target="_blank">${esc(url)}</a></span><span>${x.active?`<button class="btn small danger" data-revoke-share="${s.id}">Thu hồi</button>`:''}</span></div>`}).join(''):'<div class="empty">Chưa có liên kết.</div>';box.querySelectorAll('[data-revoke-share]').forEach(b=>b.onclick=()=>revokeShare(b.dataset.revokeShare))}).catch(()=>{box.textContent='Không tải được share'});if(mb)mb.innerHTML=state.members.map(m=>`<div class="stat-line"><span>${esc(m.email||m.uid)}</span><b>${esc(m.role)}</b></div>`).join('')||'<div class="empty">Chưa có thành viên khác.</div>'}
function openShareCreate(){if(state.view!=='share'){state.view='share';render();return}createShare()}

async function initWorkspace(user){const wr=doc(db,'workspaces',WORKSPACE),snap=await getDoc(wr);if(!snap.exists()){await setDoc(wr,{name:'GP Statistical',ownerUid:user.uid,settings:state.settings,createdAt:serverTimestamp()});await setDoc(doc(db,'workspaces',WORKSPACE,'members',user.uid),{uid:user.uid,email:user.email,displayName:user.displayName||'',role:'owner',createdAt:serverTimestamp()});state.role='owner'}else{const m=await getDoc(doc(db,'workspaces',WORKSPACE,'members',user.uid));if(m.exists())state.role=m.data().role;else{const invs=await getDocs(collection(db,'workspaces',WORKSPACE,'invites'));const inv=invs.docs.find(d=>d.data().email?.toLowerCase()===user.email.toLowerCase());if(inv){await setDoc(doc(db,'workspaces',WORKSPACE,'members',user.uid),{uid:user.uid,email:user.email,displayName:user.displayName||'',role:inv.data().role,createdAt:serverTimestamp()});state.role=inv.data().role}else{state.role=null;return}}}
const prodSnap=await getDocs(collection(db,'workspaces',WORKSPACE,'products'));if(prodSnap.empty&&state.role==='owner'){const legacy=getLegacy();if(legacy.length){for(let i=0;i<legacy.length;i+=400){const batch=writeBatch(db);legacy.slice(i,i+400).forEach(r=>batch.set(doc(db,'workspaces',WORKSPACE,'products',r.id||uid()),{...r,migratedFromLocal:true}));await batch.commit()}}await updateDoc(wr,{legacyMigrated:true,settings:state.settings,updatedAt:serverTimestamp()}).catch(()=>{})}
if(unsubProducts)unsubProducts();unsubProducts=onSnapshot(collection(db,'workspaces',WORKSPACE,'products'),qs=>{state.records=qs.docs.map(d=>d.data());cacheRecords(state.records);render()});if(unsubMembers)unsubMembers();unsubMembers=onSnapshot(collection(db,'workspaces',WORKSPACE,'members'),qs=>{state.members=qs.docs.map(d=>d.data());renderShareManagement()});}
async function openShare(id){state.shareMode=true;state.shareId=id;state.view='share';try{const s=await getDoc(doc(db,'workspaces',WORKSPACE,'shares',id));if(!s.exists()||!s.data().active){renderShareError('Liên kết chia sẻ đã bị thu hồi hoặc không tồn tại.');return}state.shareDoc={id:s.id,...s.data()};if(unsubShareProducts)unsubShareProducts();unsubShareProducts=onSnapshot(collection(db,'workspaces',WORKSPACE,'shares',id,'products'),qs=>{state.shareRecords=qs.docs.map(d=>d.data());renderShare()})}catch(e){renderShareError('Không thể mở liên kết chia sẻ.')}}
function shareFiltered(){const s=state.shareRecords,search=norm(document.querySelector('#shareSearch')?.value||'');return s.filter(r=>!search||norm(`${r.customer} ${r.productName} ${r.volume} ${r.size} ${r.designer} ${(r.editTypes||[]).join(' ')}`).includes(search))}
function renderShare(){if(!state.shareMode)return;const d=shareFiltered(),s=summary(d),editable=!!state.user&&(state.role==='owner'||state.role==='editor');root.innerHTML=`<div class="shared-page"><div class="shared-head"><div><div class="eyebrow">GP STATISTICAL · CHIA SẺ</div><h1>Danh sách sản phẩm</h1><p>Dữ liệu realtime · ${d.length} sản phẩm · ${editable?'Bạn có quyền chỉnh sửa':'Chỉ xem'}</p></div><div class="actions"><button class="btn" id="shareCopy">Chia sẻ</button><button class="btn" id="shareXlsx">Xuất Excel</button><button class="btn" id="sharePdf">Xuất PDF / A4</button>${!editable?'<button class="btn primary" id="shareLogin">Đăng nhập để chỉnh sửa</button>':'<button class="btn" id="shareBack">Về GP Statistical</button>'}</div></div>${htmlStats(d)}<div class="filters"><input id="shareSearch" class="input wide" placeholder="Tìm kiếm…" value="${esc(document.querySelector('#shareSearch')?.value||'')}"></div>${tableHtml(d,editable)}</div>`;const inp=document.querySelector('#shareSearch');if(inp){inp.oninput=()=>{state._shareSearch=inp.value;const val=inp.value;const table=shareTableOnly(val);document.querySelector('.shared-page .table-card')?.replaceWith(table)}}document.querySelector('#shareXlsx').onclick=()=>exportXlsx(d);document.querySelector('#sharePdf').onclick=()=>exportPdf(d);document.querySelector('#shareCopy').onclick=()=>navigator.clipboard?.writeText(location.href).then(()=>toast('Đã sao chép liên kết'));document.querySelector('#shareLogin')?.addEventListener('click',()=>signInWithPopup(auth,provider).catch(e=>toast(e.message)));document.querySelector('#shareBack')?.addEventListener('click',()=>{state.shareMode=false;history.pushState({},'',location.pathname);render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editShareProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteDoc(doc(db,'workspaces',WORKSPACE,'products',b.dataset.delete)))}
function shareTableOnly(search){const old=state.search;state.search=search;const d=shareFiltered();state.search=old;const wrap=document.createElement('div');wrap.innerHTML=tableHtml(d,!!state.user&&(state.role==='owner'||state.role==='editor'));return wrap.firstElementChild}
function renderShareError(msg){root.innerHTML=`<div class="gate"><div class="gate-card"><div class="gate-kicker">GP STATISTICAL</div><h1>Không thể mở.</h1><p>${esc(msg)}</p><button class="btn" id="backMain">Mở GP Statistical</button></div></div>`;document.querySelector('#backMain').onclick=()=>{state.shareMode=false;history.pushState({},'',location.pathname);render()}}
async function editShareProduct(id){if(!(state.role==='owner'||state.role==='editor'))return;const r=state.shareRecords.find(x=>x.id===id);if(!r)return;const p=prompt('Số lượng',String(r.quantity??1));if(p===null)return;const copy={...r,quantity:Number(p)||1};await upsertProduct(copy)}

function exportXlsx(data){if(!window.XLSX)return toast('Thư viện Excel chưa tải.');const s=summary(data),rows=[['BẢNG KÊ SẢN PHẨM'],[`Tháng: ${monthLabel(state.month)}`],[`Tổng số sản phẩm: ${s.products}`,'',`Tổng số lượng: ${s.qty}`],[],['STT','KHÁCH HÀNG','TÊN SẢN PHẨM','KÍCH THƯỚC','THỂ TÍCH','SỐ LƯỢNG','DESIGNER','CÔNG VIỆC','NGÀY'],...data.map((r,i)=>[i+1,r.customer||'',r.productName||'',r.size||'',r.volume||'',Number(r.quantity||0),r.designer||'',(r.editTypes||[]).join(', '),r.date||''])];const ws=XLSX.utils.aoa_to_sheet(rows),wb=XLSX.utils.book_new();ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:8}},{s:{r:1,c:0},e:{r:1,c:8}}];ws['!cols']=[{wch:7},{wch:18},{wch:38},{wch:17},{wch:12},{wch:11},{wch:16},{wch:25},{wch:13}];XLSX.utils.book_append_sheet(wb,ws,'Bảng kê');XLSX.writeFile(wb,`Bang-ke-san-pham-${state.month||'all'}.xlsx`)}
function exportPdf(data){const s=summary(data),w=window.open('','_blank','width=1200,height=900');if(!w)return toast('Trình duyệt đang chặn cửa sổ in.');w.document.write(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Bảng kê sản phẩm</title><style>@page{size:A4 landscape;margin:12mm 10mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111}h1{text-align:center;font-size:18pt;margin:0 0 2mm}.sub{text-align:center;font-size:10pt;margin-bottom:4mm}.meta{display:flex;justify-content:space-between;font-size:10pt;margin-bottom:3mm}.type{font-size:9pt;margin-bottom:4mm}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:8.5pt}th,td{border:1px solid #222;padding:2.3mm 2mm;vertical-align:middle;word-break:break-word}th{background:#eee;text-align:center}th:nth-child(1){width:8mm}th:nth-child(5),th:nth-child(6){width:19mm}th:nth-child(8){width:25mm}</style></head><body><h1>BẢNG KÊ SẢN PHẨM</h1><div class="sub">Tháng ${esc(monthLabel(state.month))}</div><div class="meta"><b>Tổng số sản phẩm: ${s.products}</b><b>Tổng số lượng: ${s.qty}</b></div>${Object.entries(s.counts).filter(([,n])=>n).length?`<div class="type"><b>Phân loại:</b> ${Object.entries(s.counts).filter(([,n])=>n).map(([k,n])=>`${esc(k)}: ${n}`).join(' | ')}</div>`:''}<table><thead><tr><th>STT</th><th>Khách hàng</th><th>Tên sản phẩm</th><th>Kích thước</th><th>Thể tích</th><th>Số lượng</th><th>Designer</th><th>Công việc</th><th>Ngày</th></tr></thead><tbody>${data.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.customer||'')}</td><td>${esc(r.productName||'')}</td><td>${esc(r.size||'')}</td><td>${esc(r.volume||'')}</td><td>${Number(r.quantity||0)}</td><td>${esc(r.designer||'')}</td><td>${esc((r.editTypes||[]).join(', '))}</td><td>${esc(r.date||'')}</td></tr>`).join('')}</tbody></table></body></html><script>window.onload=()=>setTimeout(()=>window.print(),200)</script>`);w.document.close()}
function openImage(id){const r=[...state.records,...state.shareRecords].find(r=>(r.assets||[]).some(a=>a.id===id));const a=r?.assets?.find(a=>a.id===id);if(!a)return;window.open(a.webViewLink||`https://drive.google.com/open?id=${id}`,'_blank','noopener')}
function toast(m){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}

window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#share=([A-Za-z0-9_-]+)$/);if(m)openShare(m[1]);else{state.shareMode=false;render()}});
onAuthStateChanged(auth,async user=>{state.user=user;if(unsubProducts){unsubProducts();unsubProducts=null}if(unsubMembers){unsubMembers();unsubMembers=null}if(!user){state.role=null;state.records=[];render();return}try{await initWorkspace(user);if(!state.role){renderShareError('Tài khoản này chưa được cấp quyền truy cập workspace.');return}render()}catch(e){console.error(e);toast(e.message||'Không thể khởi tạo workspace.');render()}});

function bootShare(){const m=location.hash.match(/^#share=([A-Za-z0-9_-]+)$/);if(m)openShare(m[1]);}
bootShare();
if(!state.shareMode)render();
